(
    // models
	vrs_guitar_latest: "http://victor-m1-pro:8000/ll_gtr017norm_l4_z26.ts",
	// vrs_guitar_latest: "http://localhost:8000/ll_gtr017norm_l4_z26.ts",
	// water_latest: "http://localhost:8000/ll_water_l4_z16.ts",
	// crozzoli_latest: "http://localhost:8000/ll_crozzoli_l4_z18.ts",
	// vctk_voice_latest: "http://localhost:8000/ll_vctk_voice_l4_z22.ts",
	// vocalset_voice_latest: "http://localhost:8000/ll_vocalset_voice_l4_z16.ts",
)