(
    // models
	guitar_vrs_v1: "http://victor-m1-pro:8000/ll_gtr017norm_l4_z26.ts",
	music_crozzoli_v1: "http://victor-m1-pro:8000/ll_crozzoli_l4_z18.ts",
	sax_fs_v1: "https://...",
	voice_vctk_v1: "http://victor-m1-pro:8000/ll_vctk_voice_l4_z22.ts",
	voice_vocalset_v1: "http://victor-m1-pro:8000/ll_vocalset_voice_l4_z16.ts",
	voice_multi_v1: "https://...",
	water_v1: "http://victor-m1-pro:8000/ll_water_l4_z16.ts",
	
)