(
    // models
	guitar_vrs_v1: "https://github.com/victor-shepardson/living-looper/releases/download/v1.1.0/ll_gtr017norm_l4_z26.ts",
	sax_fs_v1: "https://github.com/victor-shepardson/living-looper/releases/download/v1.1.0/ll_sax_fs_l4_z20.ts",
	voice_vocalset_v1: "https://github.com/victor-shepardson/living-looper/releases/download/v1.1.0/ll_vocalset_voice_l4_z16.ts",
	voice_multi_v1: "https://github.com/victor-shepardson/living-looper/releases/download/v1.1.0/ll_voice_multi_l4_z11.ts",
	water_v1: "https://github.com/victor-shepardson/living-looper/releases/download/v1.1.0/ll_water_l4_z16.ts",
)